config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  resources :searches, :except => [:new, :show, :edit, :update, :destroy]

  resources :schools, :except => [:index, :new, :edit, :update, :destroy] do
    resources :teachers
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :teachers
end

app/models/search.rb
class Search < ApplicationRecord
  geocoded_by :zip
  after_validation :geocode
  after_validation :reverse_geocode
  validates_presence_of :zip

  reverse_geocoded_by :latitude, :longitude do |obj,results|
  if geo = results.first
    obj.state = geo.state
  end
end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teachers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :is_admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :is_admin])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show]
  before_action :authenticate_user!

  # GET /schools/1
  def show
    
  end

  # POST /schools
  def create
    find_school = School.where(text: params[:text]).first
    if find_school
      redirect_to school_path(find_school.id)
    else
      @school = School.new(text: params[:text], latitude: params[:latitude], longitude: params[:longitude])
      if @school.save
        redirect_to school_path(@school)
      else
        render :new
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:text, :latitude, :longitude)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /searches
  def index
    # refactor so as not to start page off on last search, but on IP address loc
    @search = Search.new
    @searches = Search.all
    if @searches != nil
      @last_search = Search.last
      new_great_schools = GreatSchools.new(@last_search.latitude, @last_search.longitude, @last_search.state)
      @great_schools = new_great_schools.get_great_schools_nearby()
      # old client using google places
      # @client = GooglePlaces::Client.new(ENV['GOOGLE_API_KEY'])
      # @spots = @client.spots(@last_search.latitude, @last_search.longitude, :types => 'school')

        @hash = Gmaps4rails.build_markers(@great_schools) do |school, marker|
          marker.lat school['lat']
          marker.lng school['lon']
          marker.infowindow school['name']
          marker.json({:id => school['gsId']})
        end


    end
  end

  # POST /searches
  def create
    @search = Search.new(search_params)
    respond_to do |format|
      if @search.save
        format.html { redirect_to searches_path }
        format.js
      else
        format.html { redirect_to searches_path }
        format.js
      end
    end
  end

  private
    # callbacks
    def set_search
      @search = Search.find(params[:id])
    end

    def search_params
      params.require(:search).permit(:latitude, :longitude, :address, :zip)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @school = School.find(params[:school_id])
    @teacher = @school.teachers.new
  end

  def create
    @school = School.find(params[:school_id])
    @teacher = @school.teachers.new(teacher_params)
    @teacher.user_id = current_user.id
    @teacher.school_id = params[:school_id]
    if @teacher.save
      redirect_to school_path(@school)
    else
      render :new
    end
  end

  def edit
    @school = School.find(params[:school_id])
    @teacher = Teacher.find(params[:id])
  end

  def update
    @school = School.find(params[:school_id])
    @teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      redirect_to school_path(@school)
    else
      render :edit
    end
  end

  def show
    @school = School.find(params[:school_id])
    @teacher = Teacher.find(params[:id])
  end

  def destroy
    @school = School.find(params[:school_id])
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    redirect_to school_path(@school)
  end

private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :grade_level, :subject, :school_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/home/index.html.erb
<!-- Home#Index -->
  <section id="two">
    <div class="container">
      <header class="major">
        <h2>Graded</h2>
        <p>Create transparency.<br />
        Make the grade.</p>
      </header>
      <p>Open communication around schools, classrooms, and teachers, empowers parents and strengthens their voices. In a world where parent choice controversially creates the dynamics of our classrooms, all have the right and need to be informed. High quality education is a right.<br /> Graded helps make it a reality.</p>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Graded</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="../assets/css/main.css" />
    <%= stylesheet_link_tag    'css/main', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'searches', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Header/Sidebar -->
			<section id="header">
				<header>
					<h1 id="logo"><a href="/">Graded</a></h1>
				</header>
				<nav id="nav">
					<ul>
						<li><a href="/">Home</a></li>
            <li><%= link_to 'Search Schools', searches_path %></li>
            <hr>
            <% if user_signed_in? %>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% if current_user.is_admin %>
              <li><%= link_to "Admin", rails_admin_path %></li>
            <% end %>
              <li>Hey <%= current_user.first_name %></li>
            <% else %>
              <li><%= link_to "Sign-up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
					</ul>
				</nav>

      <!-- Sidebar Footer -->
				<footer>
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
					</ul>
				</footer>
			</section>

      <!-- Wrapper -->
			<div id="wrapper">
			<!-- Main -->
				<div id="main">
          <section id="one">
            <div class="container">
							<header class="major">
                <div class="notice">
                  <%= flash[:notice] %>
                </div>
                <div class="alert">
                  <%= flash[:alert] %>
                </div>
                <%= yield %>
              </header>
            </div>
          </section>
        </div>
      </div>


    <!-- Footer -->
      <section id="footer">
        <div class="container">
          <ul class="copyright">
            <li>&copy; 2017 Graded All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
          </ul>
        </div>
      </section>
    </body>
  </html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this @school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text, value: params[:text] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/show.html.erb
<!-- school#show -->
<!-- School Name and Static Map -->
<div class="center-static">
<h3><%= @school.text %></h3>
<div class="image">
  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=13&size=600x300&maptype=roadmap&markers=#{@school.latitude}%2C#{@school.longitude}&key=#{ENV['GOOGLE_API_KEY']}"%>
</div>


<!-- School Content NOT WORKING -->
  <div class="features">
		<article>
			<div class="inner">
          <p><%= @school['address'] %></p>
          <p><%= @school['phone'] %></p>
          <p><%= @school['gradeRange'] %></p>

						<hr>
			</div>
		</article>

<!-- Teacher Content -->
		<div class="features">
			<article>
				<div class="inner">
	        <% if @school.teachers.any? %>
	          <h4>Teachers</h4>
	          <% @school.teachers.each do |teacher| %>
							<%= link_to school_teacher_path(@school, teacher) do %>
	            <p><%=  teacher.first_name %> <%=  teacher.last_name %></p>
							<% end %>
	            <% if teacher.user_id == current_user.id %>
	              <%= link_to "Edit", edit_school_teacher_path(@school, teacher.id) %>
	              <%= link_to "Delete", school_teacher_path(@school, teacher.id), method: :delete %>
	            <% end %>
							<hr>
	          <% end %>
	          <br>
	        <% else %>
	          <p>Be the first to add teacher to <%= @school.text %></p>
	        <% end %>
				</div>
			</article>

		<!-- New Teacher Link -->
	    <%= link_to "New Teacher", new_school_teacher_path(@school) %>

		<hr>
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/searches/_form.html.erb
<%= form_for @search do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this @search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="search-field">
  <div class="input-field" id="zip-input">
   <%= f.number_field :zip, id: "search", type: "text", placeholder: "Zip Code"%>
  </div>


  <div class="actions" id="zip-submit">
    <%= f.button :submit, id: "search" do %>
    <ul class="feature-icons">
      <li class="fa-search fa-lg">
      </li>
    </ul>
    <% end %>

  </div>
</div>
<% end %>

app/views/searches/_search.html.erb
<!-- Search Form w/ search icon -->

  <%= render "form", search: @search%>

app/views/searches/index.html.erb
<script src="//maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY']%>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script src='//cdn.rawgit.com/googlemaps/js-rich-marker/gh-pages/src/richmarker-compiled.js' type='text/javascript'></script>

<!-- Search by Zip with Map -->
<div class="center-static">
  <h3>Find Schools Near You</h3>
  <p>Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer lorem ipsum dolor sit amet.</p>

  <!-- Search Partial -->
  <div id="search-form">
    <%= render "search" %>
  </div>

  <!-- Dynamic Map -->
  <div id="map" class="image" style='width: 600px; height: 400px;'></div>

  <!-- List of Search Results -->
  <% if @searches.any? %>
    <h4>Schools</h4>
    <% @great_schools.each do |school| %>
        <%= link_to schools_path(text: school['name'], latitude: school['lat'], longitude: school['lon']), method: "post" do %>
          <p id="new-search"><%= school['name'] %></p>
        <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Schools", schools_path %>


<!-- Build Map JS -->
<script type="text/javascript">
buildMap(<%=raw @hash.to_json %>);
</script>

app/views/teachers/_form.html.erb
<%= form_for [@school, @teacher] do |f| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
  </div>

  <div class="field">
    <%= f.label :grade_level %>
    <%= f.text_field :grade_level %><br>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', school_teacher_path(@school, @teacher) %> |
<%= link_to 'Back', school_path(@school) %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', school_path(@school) %>

app/views/teachers/show.html.erb
<div class="features">
  <article>
    <div class="inner">
      <h4><%= @teacher.first_name %> <%= @teacher.last_name %></h4>
      <p>Grade: <%=  @teacher.grade_level %></p>
      <p>Subject: <%=  @teacher.subject %></p>
    </div>
  </article>

  <hr>

  <div class="features">
    <article>
      <div class="inner">
          <h4>Teacher</h4>
      </div>
    </article>
<hr>
<div class="center-static">
  <%= link_to 'Edit Teacher', edit_school_teacher_path(@school, @teacher) %> |
  <%= link_to 'Back', school_path(@school) %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>